"""remove progress and attempts

Revision ID: c0fc41c60dfe
Revises: 
Create Date: 2026-04-23 07:31:41.296688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0fc41c60dfe'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('queued', 'preprocessing', 'running', 'completed', 'failed', 'timed_out', name='analysis_status', native_enum=False), nullable=False),
    sa.Column('progress_stage', sa.Enum('queued', 'preprocessing', 'running', 'completed', 'failed', 'timed_out', name='analysis_progress_stage', native_enum=False), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('audio_name', sa.String(length=512), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analysis'))
    )
    op.create_index(op.f('ix_analysis_created_at'), 'analysis', ['created_at'], unique=False)
    op.create_index(op.f('ix_analysis_expires_at'), 'analysis', ['expires_at'], unique=False)
    op.create_index('ix_analysis_idempotency_key', 'analysis', ['idempotency_key'], unique=True, postgresql_where=sa.text('idempotency_key IS NOT NULL'))
    op.create_index(op.f('ix_analysis_status'), 'analysis', ['status'], unique=False)
    op.create_index(op.f('ix_analysis_user_id'), 'analysis', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analysis_user_id'), table_name='analysis')
    op.drop_index(op.f('ix_analysis_status'), table_name='analysis')
    op.drop_index('ix_analysis_idempotency_key', table_name='analysis', postgresql_where=sa.text('idempotency_key IS NOT NULL'))
    op.drop_index(op.f('ix_analysis_expires_at'), table_name='analysis')
    op.drop_index(op.f('ix_analysis_created_at'), table_name='analysis')
    op.drop_table('analysis')
    op.execute('DROP TYPE analysis_status')
    op.execute('DROP TYPE analysis_progress_stage')
    # ### end Alembic commands ###
